server:
  port: 8080
  servlet:
    context-path: /api

spring:
  cache:
    type: redis
  main:
    allow-bean-definition-overriding: true
  application:
    name: payment
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://103.70.13.202:5432/api_redis
    username: postgres
    password: Qwertyu1@
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 25
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      schema: public
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.batch_size: 1000
        order_inserts: true
        default_schema: public
  data:
    redis:
      host: 103.70.13.202
      port: 6379
      password: Qwertyu1@